# Start configure_vpn for provider csr
---
- name: Create IKev2 profile
  cisco.ios.ios_config:
    lines:
      - "match identity remote fqdn domain {{ configuration.vpn_profile.remote_fqdn }}"
      - "identity local fqdn {{ configuration.vpn_profile.local_fqdn }}"
      - "authentication remote pre-share key {{ configuration.vpn_profile.authentication.remote_psk }}"
      - "authentication local pre-share key {{ configuration.vpn_profile.authentication.local_psk }}"
    parents: "crypto ikev2 profile {{ configuration.vpn_profile.name }}"

- name: Build tunnel interface configuration
  ansible.builtin.set_fact:
    tunnel_config: 
      - "tunnel source {{ configuration.tunnel_interface.source }}"
      - "tunnel destination {{ configuration.tunnel_interface.destination }}"
      - "tunnel protection ipsec profile {{ configuration.vpn_profile.name }}"
    ipv4: []
    ipv6: []

- name: Add ipv4 address to tunnel configuration (if defined)
  ansible.builtin.set_fact:
    tunnel_config: "{{ tunnel_config + ['ip address {{ configuration.tunnel_interface.ipv4.address }} {{ configuration.tunnel_interface.ipv4.netmask }}'] }}"
  when: configuration.tunnel_interface.ipv4 is defined

- name: Add ipv6 address to tunnel configuration (if defined)
  ansible.builtin.set_fact:
    tunnel_config: "{{ tunnel_config + ['ipv6 address {{ configuration.tunnel_interface.ipv6.address }} {{ configuration.tunnel_interface.ipv6.netmask }}'] }}"
  when: configuration.tunnel_interface.ipv6 is defined

- name: "Create tunnel interface - {{ configuration.tunnel_interface.name }} with provided configuration"
  cisco.ios.ios_config:
    lines: "{{ tunnel_config }}"
    parents: "interface {{ configuration.tunnel_interface.name }}"

- name: "Bring up tunnel interface - {{ configuration.tunnel_interface.name }}"
  cisco.ios.ios_config:
    lines: "no shutdown"
    parents: "interface {{ configuration.tunnel_interface.name }}"
  changed_when: False

- name: Set DPD values
  cisco.ios.ios_config:
    lines: "crypto ikev2 dpd {{ configuration.dead_peer_detection.interval }} {{ configuration.dead_peer_detection.retry }} on-demand"
  when: configuration.dead_peer_detection is defined
